"""Generate the private Phase 5 capture dispatch table.

Reads the private generated root's ``symbol_inventory.json`` and writes a
C++ include file mapping every normal callable symbol name to its function
pointer.  The output lives in the build tree (never tracked): the table
itself is derived from ROM-backed generation and stays local per the Phase 5
acceptance contract's data boundary.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

_SYMBOL_PATTERN = re.compile(r"^[A-Za-z_][A-Za-z0-9_]{0,127}$")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--generated-root", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    arguments = parser.parse_args()

    inventory_path = arguments.generated_root / "symbol_inventory.json"
    inventory = json.loads(inventory_path.read_text(encoding="utf-8"))
    if inventory.get("version") not in {1, 2}:
        print("unsupported symbol inventory version", file=sys.stderr)
        return 1
    symbols = inventory.get("normal_callable_symbols")
    if not isinstance(symbols, list) or not symbols:
        print("missing normal_callable_symbols", file=sys.stderr)
        return 1
    for symbol in symbols:
        if not isinstance(symbol, str) or not _SYMBOL_PATTERN.match(symbol):
            print(f"rejected symbol name: {symbol!r}", file=sys.stderr)
            return 1

    lines = [
        "// Generated by scripts/prepare_phase5_capture_table.py.",
        "// Derived from the private generated root; never tracked.",
        "#pragma once",
        "",
    ]
    for symbol in symbols:
        lines.append(
            f'extern "C" void {symbol}(uint8_t* rdram, recomp_context* ctx);'
        )
    lines.append("")
    lines.append("struct Phase5CaptureEntry {")
    lines.append("    const char* name;")
    lines.append("    void (*function)(uint8_t*, recomp_context*);")
    lines.append("};")
    lines.append("")
    lines.append("inline constexpr Phase5CaptureEntry kPhase5CaptureTable[] = {")
    for symbol in symbols:
        lines.append(f'    {{"{symbol}", &{symbol}}},')
    lines.append("};")
    lines.append("")

    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    arguments.output.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {len(symbols)} entries to {arguments.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
