# Honor the original game's VI scanout aspect without changing its camera.
set(jfg_vi_source "${jfg_rt64_root}/src/render/rt64_vi_renderer.cpp")
file(SHA256 "${jfg_vi_source}" jfg_vi_hash)
if(NOT jfg_vi_hash STREQUAL "0159b441fd4872ef30a49d7603f4570d8858084004c20dd6646f51039241fa7b" AND NOT jfg_vi_hash STREQUAL "e5bf1f4a7983839f92a2abe588602f793681a04f9c959fce8ad68a6b2b9dcc20")
    message(FATAL_ERROR "Pinned RT64 VI renderer differs from the audited presentation input")
endif()
file(READ "${jfg_vi_source}" jfg_vi_contents)
set(jfg_vi_old "const hlslpp::float2 hdSize = computeHDSize(sdSize, resolutionScale, downsamplingScale);")
set(jfg_vi_new [=[hlslpp::float2 hdSize = computeHDSize(sdSize, resolutionScale, downsamplingScale);
        const auto display = jfg::vi_presentation_size(vi.hRegion.word, vi.vRegion.word);
        if (removeBlackBorders && display.valid() && resolutionScale.y > 0.0f) {
            hdSize.x = hdSize.y * float(display.width) / float(display.height)
                * resolutionScale.x / resolutionScale.y;
        }]=])
string(FIND "${jfg_vi_contents}" "${jfg_vi_old}" jfg_vi_offset)
if(jfg_vi_offset EQUAL -1)
    message(FATAL_ERROR "Pinned RT64 VI presentation patch site is missing")
endif()
string(REPLACE "${jfg_vi_old}" "${jfg_vi_new}" jfg_vi_contents "${jfg_vi_contents}")
set(jfg_vi_generated "${CMAKE_CURRENT_BINARY_DIR}/generated/rt64/render/rt64_vi_renderer.cpp")
file(WRITE "${jfg_vi_generated}" "#include \"jfg/renderer/vi_presentation.hpp\"\n${jfg_vi_contents}")
get_target_property(jfg_vi_sources rt64 SOURCES)
set(jfg_vi_patched_sources)
set(jfg_vi_replaced FALSE)
foreach(jfg_vi_unit IN LISTS jfg_vi_sources)
    if(jfg_vi_unit MATCHES "(^|[/\\\\])rt64_vi_renderer\\.cpp$")
        list(APPEND jfg_vi_patched_sources "${jfg_vi_generated}")
        set(jfg_vi_replaced TRUE)
    else()
        list(APPEND jfg_vi_patched_sources "${jfg_vi_unit}")
    endif()
endforeach()
if(NOT jfg_vi_replaced)
    message(FATAL_ERROR "Pinned RT64 target is missing its VI renderer")
endif()
set_property(TARGET rt64 PROPERTY SOURCES "${jfg_vi_patched_sources}")
target_include_directories(rt64 PRIVATE "${PROJECT_SOURCE_DIR}/include")
