# Raw RDP set-other-mode commands can differ from the RSP mode stack.
# Track depth bounds with the effective mode used by the actual draw call,
# otherwise depth writes may never be copied back for game visibility checks.
set(jfg_depth_bounds_source "${jfg_rt64_root}/src/hle/rt64_rsp.cpp")
file(SHA256 "${jfg_depth_bounds_source}" jfg_depth_bounds_hash)
if(NOT jfg_depth_bounds_hash STREQUAL "7dfdf40254d44d92c247d9c876bb8ca55995927ad534981bd48868bb44f1f695")
    message(FATAL_ERROR "Pinned RT64 RSP differs from the audited depth-bounds input")
endif()
file(READ "${jfg_depth_bounds_source}" jfg_depth_bounds_contents)
set(jfg_depth_bounds_old "if (otherModeStack[otherModeStackSize - 1].zUpd()) {")
set(jfg_depth_bounds_new "if (state->rdp->otherMode.zUpd()) {")
string(FIND "${jfg_depth_bounds_contents}" "${jfg_depth_bounds_old}" jfg_depth_bounds_first)
string(FIND "${jfg_depth_bounds_contents}" "${jfg_depth_bounds_old}" jfg_depth_bounds_last REVERSE)
if(jfg_depth_bounds_first EQUAL -1 OR NOT jfg_depth_bounds_first EQUAL jfg_depth_bounds_last)
    message(FATAL_ERROR "Pinned RT64 depth-bounds patch site is missing or ambiguous")
endif()
string(REPLACE "${jfg_depth_bounds_old}" "${jfg_depth_bounds_new}"
    jfg_depth_bounds_contents "${jfg_depth_bounds_contents}")
set(jfg_depth_bounds_generated "${CMAKE_CURRENT_BINARY_DIR}/generated/rt64/hle/rt64_rsp.cpp")
file(WRITE "${jfg_depth_bounds_generated}" "${jfg_depth_bounds_contents}")
get_target_property(jfg_depth_bounds_sources rt64 SOURCES)
set(jfg_depth_bounds_patched_sources)
set(jfg_depth_bounds_replaced FALSE)
foreach(jfg_depth_bounds_unit IN LISTS jfg_depth_bounds_sources)
    if(jfg_depth_bounds_unit MATCHES "(^|[/\\\\])rt64_rsp\\.cpp$")
        list(APPEND jfg_depth_bounds_patched_sources "${jfg_depth_bounds_generated}")
        set(jfg_depth_bounds_replaced TRUE)
    else()
        list(APPEND jfg_depth_bounds_patched_sources "${jfg_depth_bounds_unit}")
    endif()
endforeach()
if(NOT jfg_depth_bounds_replaced)
    message(FATAL_ERROR "Pinned RT64 target is missing its RSP translation unit")
endif()
set_property(TARGET rt64 PROPERTY SOURCES "${jfg_depth_bounds_patched_sources}")
# Preserve quoted and relative header lookup for the generated translation unit.
target_include_directories(rt64 PRIVATE "${jfg_rt64_root}/src/hle")
